@startuml
title
""Pattern: `(a$|b)c`""
end title

skinparam rectangle {
  BorderColor #888888
  BackgroundColor #F8F8FF
  FontStyle bold
}

component """BEGIN""" as node_BEGIN_4
component """END""" as node_END_5

rectangle "Sequence: (b)c" {
  rectangle "Group 1: (b)" {
    component """FinalSymbol(b) """ as node_AST_2
  }
  component """FinalSymbol(c) """ as node_AST_3
}

node_BEGIN_4 --> node_AST_2
node_AST_2 --> node_AST_3
node_AST_3 --> node_END_5
}
@enduml
